### ISSUE TITLE
GI Bill CT Data Service is stripping quotes around OPE IDs

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#304] opened 2017-10-25 07:57 UTC
When a user clicks on the "download export csv" file, the GI Bill CT file is missing the quotes around the OPE ID numbers. For example American Public University (FC #21913148) should have an OPE ID "03819300" but the export file says [3819300].

This is problematic because most OPE ID's start with zeros and therefore the number  of characters for this field in csv changes.  Downstream this messes up many of the calculations for the GI Bill CT Data Dashboards because OPE IDs are use to group calculations for "All campuses"

This was an issue before #84 that was resolved but it appears to have come back again.

@leannammiller @mphprogrammer @patrickvinograd

**Comment by mphprogrammer** [comment] 2017-10-25 15:55
Sorry about that, in the meantime,  in the XLS you can format the column using custom and entering in "00000000", and change the column type to text - I think that works.

**Comment by saintsoup52** [comment] 2017-10-25 18:19
Unfortunately changing the formatting in excel doesn't change the calculation issues.

Thank you for looking at this.

**Comment by saintsoup52** [comment] 2017-11-07 15:15
Sorry to bug, but has there been any update on this issue?

**Comment by jmcneal65** [comment] 2017-11-07 15:27
Morning P,

First, are you back in the world?

Secondly, let me check with leanna on this…

With best personal regards,

       John

John T. McNeal
U.S. Department of Veterans Affairs
Veterans Benefits Administration, Office of Education Service
Business Process Development – Legacy Systems (224B)
Office: 202.461.9613 | iPhone: 202-957-2281





Confidentiality Notice: If you received this email by mistake, you should notify the sender of the mistake and delete the email and any attachments. An inadvertent disclosure is not intended to waive any privileges.

**Comment by mphprogrammer** [comment] 2017-11-09 15:23
@saintsoup52 This is only ope we are talking about, or is it cross and fac codes too?

**Comment by saintsoup52** [comment] 2017-11-09 15:24
Just OPE... the other numbers don't have IDs that start with zeroes so this isn't a problem anywhere else.

**Comment by saneshark** [comment] 2017-11-09 16:05
@saintsoup52 If I understand correctly, the issue is with Excel, not with the CSV export. Currently vets.gov is in effect returning everything as a String. Excel happens to automatically make assumptions about field type. I characterize the fact that everything is currently returned in a consistent manner as a feature, not a bug. If we were quoting certain fields/columns elsewhere, then I agree that this would constitute a bug.

**Comment by saneshark** [comment] 2017-11-09 16:14
If we need to take a more holistic look and reevaluate how the CSV is exported in the future that is fine. But in the meantime, I think you can just change the file extension to be export.csv.txt and Excel will not automatically convert anything. Additionally, you could select the column in question, select "Format Cells" and specify the type of column as "text." Other than that, I'm afraid that we do not have the capacity / resources to support adding and testing additional new features currently.

**Comment by saintsoup52** [comment] 2017-11-09 16:42
The problem is that we need the exported file to support the data dashboards that are in excel. We can't just save it as a csv file because, csv files can't have more than one tab in excel.

As we have discussed those dashboards are downloaded thousands of times and are used by DOD to approve schools for Military tuition assistance. Veterans groups use this data for all sorts of purposes and not having those quotes makes life very difficult for them.

This has always been a requirement for the data service... as I mentioned we had this exact same issue last year that eventually got resolved.
https://github.com/department-of-veterans-affairs/gibct-data-service/issues/84 

To put a finer point on it... VA is currently giving out incorrect data to the public because of this issue.  VA has received complaints from external stakeholders about this.

**Comment by saneshark** [comment] 2017-11-09 17:27
My point is that it does support this or any behavior you would need. It just has the added step of requiring you to specify formatting of specific columns within Excel. It's not like the actual plain text version of the CSV is missing the leading zeros. It's entirely an issue with Excel interpreting what should be interpreted as a string as number.

**Comment by saintsoup52** [comment] 2017-11-09 18:20
The equations that we use to roll up the GI Bill data by OPE ID doesn't work without the quotations. Even if we do the formatting you suggest, we can't cut and paste the data and run the equations at the same time. For example, when we were using single quotations this also became an issue: See #133 

Additionally... When Dept of ED publishes OPE data they also enclose them in double quotations for the exact same reason we do. As soon as anyone copies the data from our spreadsheet into their own the data changes and messes everything up. It literally takes hours to undo and one stakeholder told me this morning they are starting to have nightmares about dealing with our data because of this exact issue.

I don't know what more to say... this has always been a requirement with the DS... It used to work and for some reason it stopped.

**Comment by saneshark** [comment] 2017-11-09 18:51
I don't know what else there is to say here. The problem is with Excel not with the export. The export is in proper CSV format and we very simply do not have resources to address this at this time. 

Rather than double clicking the CSV file and having it automatically open, my suggestion is to change the extension to .txt. Then when you open the file in Excel it will trigger the Text Import Wizard. There you can specify types for columns. This would be the correct workaround for Excel's overzealous interpretation of types for columns of data. Any change to the export by wrapping the field in quotes is a hack simply to address an issue that exists in Excel.

**Comment by jmcneal65** [comment] 2018-02-27 14:44
DS, 
Where are we with this issue?  This has become a problem with accurate of CT data.

**Comment by jkassemi** [comment] 2018-06-04 11:07
@saintsoup52, @jmcneal65 - apologies, I thought we'd had a fix ready for review on this one.

I have what might be a dumb question, but I'm testing a few solutions to this locally, and even _with_ quotes around the OPE ID, Excel (16.13.1 on my system) doesn't appear to treat the value as a string. Is there a way you're specifying data formatting or making any changes that make this work differently on your end? I'm attaching a sample CSV export that's fully quoted for feedback (zipped since GitHub won't support the original extension).

[SampleFullyQuoted.csv.zip](https://github.com/department-of-veterans-affairs/gibct-data-service/files/2067960/SampleFullyQuoted.csv.zip)

**Comment by saintsoup52** [comment] 2018-06-04 15:58
I am not making any specifications in the data... I am also not treating it as a number for any particular reason. I just use it for matching. Hope that helps.

**Comment by briangryth** [comment] 2018-08-09 16:41
Just received information from @saintsoup52 that this issue is still occurring. It is causing a strain on EDU staff to fix the problem manually. 

@jkassemi is this something that @lihanli can look into. 

@rtluu can you work with Matt Self to prioritize this work ASAP.

**Comment by jkassemi** [comment] 2018-08-09 17:40
@briangryth yes, @lihanli can address as prioritized by @rtluu and Matt Self. 

My earlier testing indicated that the approach detailed in https://superuser.com/a/318421 would be effective. I have not estimated the effort or planned the implementation of that approach for GIDS.

**Comment by saintsoup52** [comment] 2018-08-09 19:05
Thank you for taking another look at this... @jkassemi @lihanli @rtluu 

Just to be clear this issue appears in two places:
1) When the **crosswalk** is uploaded with the quotations in the OPE field and then that same is exported out of the GIDS the quotes are gone.

2) Also when the **full GI Bill CT file** is exported the OPE field is missing the quotes around the OPE ID fields

Hope that helps.

**Comment by rtluu** [comment] 2018-08-09 19:54
@jholton here is some more context as to where this issue is occurring

> This issue appears in two places:
> 
> 1. When the crosswalk is uploaded with the quotations in the OPE field and then that same is exported out of the GIDS the quotes are gone.
> 2. Also when the full GI Bill CT file is exported the OPE field is missing the quotes around the OPE ID fields

**Comment by jholton** [comment] 2018-08-10 15:01
Should we add quotes around OPE for all exports, or only the two specific exports mentioned?

**Comment by briangryth** [comment] 2018-08-10 21:32
@jholton - definitely for the two specific exports. Not sure about others. 

@saintsoup52 can you confirm whether we need to add the quotes on all exports or not?

**Comment by saintsoup52** [comment] 2018-08-13 14:12
@jholton Beside the two files that we already mentioned (crosswalk and the data dashboard), OPE is used in a couple of different places.

For example:
* WEAMS 
* Eight keys
* HCM
* MOU
* Scorecard

The three files that VA owns (WEAMS, crosswalk, and the final CT file) are the most important because those are VA files that are kept and managed within the data service.

**Comment by jholton** [comment] 2018-08-16 20:38
@saintsoup52 the PR has been merged and we'll get it deployed tomorrow morning.  I'll follow up again when it's done.

**Comment by jholton** [comment] 2018-08-17 17:01
@saintsoup52 the changes have been deployed to production. 

Let us know if you have any further issues.

Thanks!

**Closed as completed** 2018-08-17 17:01 UTC

**Comment by saintsoup52** [comment] 2018-08-19 01:59
I just double checked this... thank you so much for fixing this!!
