### ISSUE TITLE
Housing Allowance by Zip Code 

### ISSUE THREAD

**Issue by briangryth** [department-of-veterans-affairs/gibct-data-service#324] opened 2018-05-10 04:34 UTC
As part of the Comery Act changes the GIBCT is required to allow a Veteran to be paid the housing allowance according to where a credit is obtained (e.g. paid at the rate for the city where an internship is  taken). This housing allowance by ZIP code is not currently in the GIDS. Thus, we need to add that file to the GIDS and make the data accessible to the GIBCT front end

**New Data Files**

[BAH Rates 2017_18.csv.zip](https://github.com/department-of-veterans-affairs/gibct-data-service/files/1990371/BAH.Rates.2017_18.csv.zip)
[LTS_EDU_DOD_BAH_RATES_2018-2019_05022018.txt](https://github.com/department-of-veterans-affairs/gibct-data-service/files/1990373/LTS_EDU_DOD_BAH_RATES_2018-2019_05022018.txt)
[LTS_EDU_ZIPMHA_2018-2019_05022018.txt](https://github.com/department-of-veterans-affairs/gibct-data-service/files/1990374/LTS_EDU_ZIPMHA_2018-2019_05022018.txt)

**Note from Patrick C and Education Services staff**
Housing Allowance rates by zip code (with grandfathered rates)
- I put this together myself… EDU might want to organize it in another way, but this it will be something like this
- You will see that I had to put quotes around the zips so the leading zeroes didn’t drop off… sorry
- We should be sure to have error codes if the zip codes aren’t found in our list or the rates return as zero

*Vets.gov-team related ticket* - [Issue #9368](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9368)

**Comment by maneshkommidi** [comment] 2018-05-21 20:00
@briangryth @saintsoup52 could you please let me know what is the use of .txt files(LTS_EDU_DOD_BAH_RATES_2018-2019_05022018.txt, LTS_EDU_ZIPMHA_2018-2019_05022018.txt)

**Comment by jkassemi** [comment] 2018-05-29 21:39
@maneshkommidi, will also need an implementation plan for this functionality to assist with assessing delays.

**Comment by maneshkommidi** [comment] 2018-05-31 13:46
@jkassemi as already related migrations are merged in, know we need to implement search functionality based on zip code.

**Comment by saneshark** [comment] 2018-06-12 21:52
@saintsoup52 for now, I am going to manually merge these two files into 1 and populate the table using a rake task. I will not introduce the functionality to do this via upload until we have a chance to discuss this further. I think that should be OK since it appears these do not get updated very regularly.

Question for you: Can these rates be manually merged into a single CSV to be used in populating our zipcode_rates table in the future? I think that's going to be ideal. Uploading two separate sets of csv to build a single table isn't practical. I realize we already do it for institutions table, but that's different. I'm not saying it can't be done, but for now there are UI/design constraints that I do not have the time to think through.

What are your thoughts? In the future, could we get a single comma separated file that includes the information needed? I think this can easily be achieved with an excel file that does an Hlookup, and then generate a CSV based on that result.

Alternately, if the zipcodes and MHA values are static and will never change, we could seed the database with those values from the first file, and then an upload would just update rates for all MHA's, but I'm thinking MHAs could possibly change in the future for a given zip code.

A single file would contain the following data, based on the headers below:
```
zip_code, mha_code, mha_name, mha_rate, mha_rate_grandfathered
```
The zip code should be properly escaped with quotations so that leading zeros are not dropped off.

**Comment by saneshark** [comment] 2018-06-12 23:32
I'm not sure how mha_name is used, historically this would be `City, State`, and while I realize a single zip code might often encompass multiple geographic areas, usually there is a primary city that is associated with a zip code. Can we ensure that is always available in the data set as well? 

I can try to build it from this source for now, but I am not entirely sure how reliable this database is.
http://federalgovernmentzipcodes.us/

is this column even required?

**Comment by saintsoup52** [comment] 2018-06-13 21:34
There is a crosswalk between zip codes and MHA names... those names take into consideration zip codes that cover multiple cities.

**Comment by saintsoup52** [comment] 2018-06-13 21:47
@saneshark We could manually do the match on our end to create your end result.

**Comment by jkassemi** [comment] 2018-06-13 22:00
@saintsoup52 - apologies if I'm missing something, but is that a source we're already using or one that we have access to and has already been provided? Cursory scan of issues / source isn't pulling anything up. 

I'm also trying to understand where the MHA name is used - are we considering it just for display under where the Veteran provides their zip code to confirm the location (https://user-images.githubusercontent.com/4106356/39538897-1b484234-4df3-11e8-87bf-ccfa660dd07e.png)?

It sounds like we still have enough to provide a response schema for our endpoint changes, so my recommendation would be to roll forward with #339 (including the name from the https://github.com/department-of-veterans-affairs/gibct-data-service/blob/1b0bfc04754dcd5fcdbca4d0542b87121ec1f647/sample_csvs/zipcode_rate.csv file that @maneshkommidi included) while we flesh out details to prevent blocking the FE implementation.

**Comment by saintsoup52** [comment] 2018-06-14 12:33
Here is the combined BAH file we should be using for the upload... the attachment below includes the MHA names (where they exist).

[BAH Rates 2017_18.xlsx](https://github.com/department-of-veterans-affairs/gibct-data-service/files/2102319/BAH.Rates.2017_18.xlsx)

**Comment by jkassemi** [comment] 2018-06-14 16:13
Thanks @saintsoup52. I see a few zips without rates - can you clarify on expected behavior if those zip codes are entered by the Veteran?

**Comment by saneshark** [comment] 2018-06-14 22:29
Also @saintsoup52 it appears as though the xls file you just provided has different rates than the rates I was able to derive for a given zip code based on the two files you sent earlier. Almost all of them appear to be different.

**Comment by saintsoup52** [comment] 2018-06-15 02:08
@jkassemi If there is no rate then the tool should say something like zip code not recognized.

@saneshark The rates are different because the file I just uploaded are valid through July 31, 2018. The ones I uploaded earlier are the rates that will take affect August 1st, 2018. For the time being we should just be using the rates I just uploaded (BAH Rates 2017_18) because that was the file provided from EDU.

**Closed as completed** 2018-06-22 15:47 UTC
