### ISSUE TITLE
Create migration to support adding column to WEAMS file and the corresponding migration for changes to institutions table.

### ISSUE THREAD

**Issue by briangryth** [department-of-veterans-affairs/gibct-data-service#336] opened 2018-06-12 20:51 UTC
The migration for the WEAMS file needs to be update to include following new columns:
·         Priority Enrollment
·         Online Only
·         Independent Study
·         Distance Learning

Corresponding changes need to be made to the Institution table.

Sample of the new WEAMS file. 

[WEAMS Extract expanded clean.zip](https://github.com/department-of-veterans-affairs/gibct-data-service/files/2095808/WEAMS.Extract.expanded.clean.zip)

**Comment by saneshark** [comment] 2018-06-14 02:05
Questions:
1. I have downloaded the extract, it appears as though all of the values for the newly created columns are Null. There is no real data available other than the column headers in the above extract. Is this by design or should there be T / F values for some of these?

2. Should Null be interpreted as false?

3. Do we have to continue supporting the possibility that an old style WEAMS csv would get uploaded? Or moving forward after this code is merged can we expect that only CSVs with appropriate columns available will be uploaded (NOTE it will be much lower effort if we dont need to be backward compatible with legacy CSV uploads).

**Comment by briangryth** [comment] 2018-06-14 17:58
Okay here is the information I know:

Question 2. Should Null be interpreted as false?

Answer: According to the WEAMS additions requirements (see below), the value can be "True or False or Null". However, on the front-end we will treat Null as false and not display the Independent Study and Priority Enrollment indicators. Thus, we need to support a file have a NULL value, but I don't see a problem interpreting that as false. 

[Requirments PIR 18-051 - Task 613055 -  Add Checkboxes to COMP tool Interface.pdf](https://github.com/department-of-veterans-affairs/gibct-data-service/files/2103413/Requirments.PIR.18-051.-.Task.613055.-.Add.Checkboxes.to.COMP.tool.Interface.pdf)

Question 3. Do we have to continue supporting the possibility that an old style WEAMS csv would get uploaded? Or moving forward after this code is merged can we expect that only CSVs with appropriate columns available will be uploaded (NOTE it will be much lower effort if we dont need to be backward compatible with legacy CSV uploads).

Answer: My understanding is that we would have to support the old style WEAMS csv, which is not ideal. The WEAMS system that generates the file is being updated later this year (maybe as early in the summer). Until then we have to be backward compatible. Also on this item @saintsoup52 has stated in emails that

> Please remember that these columns will be implemented in stages (a couple now and others down the road). So please do not make these new columns “required” when the WEAMS file is uploaded otherwise this will all cause a mess.

As for your Question 1, I will have to check with Shay from Education Services to see if they have a file with true and false data.

I hope that helps.

**Comment by saintsoup52** [comment] 2018-06-14 18:42
1. I have downloaded the extract, it appears as though all of the values for the newly created columns are Null. There is no real data available other than the column headers in the above extract. Is this by design or should there be T / F values for some of these?

There is only data in two of the columns right now "Priority Enrollment" (436) and "Independent Study"(213)... the rest of the new data points will be NULL right now.

**Comment by briangryth** [comment] 2018-06-15 16:19
@saneshark - I looked at the CSV again and it appears that there are some "Y" (which I'm assume equals "true") in Priority Enrollment and Independent Study column. But the column are mostly "Null". 

I sent a question to EDU staff and Patrick Campbell (i.e. @saintsoup52) regarding the file. However, tagged Patrick here to see if he can provide further insight into your questions.

**Comment by saintsoup52** [comment] 2018-06-15 16:51
@briangryth @saneshark Sorry about the "Y" versus True's... that was me. Y does mean True. Most of the schools will be NULL.

Since I am manually adding those columns to the WEAMS file... should we just change the "Y" to "True" and then go forth?

**Comment by saneshark** [comment] 2018-06-15 21:31
It won't matter either way from our standpoint, as long as we're consistent.

**Closed as completed** 2018-06-22 15:59 UTC
