### ISSUE TITLE
Error uploading files missing non-critical columns or too many columns

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#256] opened 2017-04-12 12:25 UTC
I tried uploading the directory file from IPEDS, AKA "Ipeds Hd" and I got the following error message.

"Failed to upload HD2015 20170412.csv.

IpedsHd has an issue with headers. Missing headers: ccipug, ccipgrad, ccugprof, ccenrprf, ccsizset. Extra headers: c15basic, c15ipug, c15ipgrd, c15ugprf, c15enprf, c15szset."

None of the missing columns are used in the DS and therefore I thought they should not be causing a critical error when they are missing.

Additionally, we had talked about not causing errors when files might have additional columns as well.

Many times non VA files like IPEDS, Accreditation, 8-keys, HCM, etc. will get rid of data points have new data points that we do not use. Requiring updates to the data service each time this happens will cause a significant workload.

![image](https://cloud.githubusercontent.com/assets/4397508/24957275/3176a8e4-1f59-11e7-9432-fdbe94d500ad.png)

@mphprogrammer @saneshark

**Comment by mphprogrammer** [comment] 2017-04-12 15:38
They do because of the way the data service intakes data. It expects to see all columns taken into the source (Weam, Crosswalk, ...) CSV data present with no additional fields. How often does this happen? This is something we need to know, because the admins may not know if we use any columns internally...

**Comment by mphprogrammer** [comment] 2017-04-12 15:41
If this happens on a monthly, or more frequent basis, this may become an issue ...

**Comment by saneshark** [comment] 2017-04-12 15:51
@saintsoup52 - it will not require an update to the data service. Admins uploading files should know that they cannot just remove columns. We're trying to deliver some consistency here. Removing or adding arbitrary columns **should** break the upload. Until there is some automated data integrity, this is a necessary safety measure. I'm with @mphprogrammer on this one.

Please feel free to close the issue or provide additional arguments against this.

**Comment by patrickvinograd** [comment] 2017-04-12 16:50
To @saintsoup52 's point, we did discuss tolerating net-new columns after our phone call in February, because I made an issue to track it: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1265

**Comment by saneshark** [comment] 2017-04-12 17:47
Noted. Because stakeholders will be getting a helpful warning detailing precisely what is wrong with their upload, I am chrachterizing this as a feature not a bug. Closing.

**Comment by saintsoup52** [comment] 2017-04-12 17:53
Sorry that I am late to the party... This is an issue because VA does not control half of the data that is uploaded to the data service. So ED changes the format of their files regularly, case in point the IPEDS files I tried to upload.

My remaining question is, "Does the order of columns make a difference?"

Getting a error that you are missing 2-3 columns out of 50-60 is easily fixed if you can just add those column names at the end of the file. But if you actually have to get them back in the correct order is a LOT of work.

**Comment by saneshark** [comment] 2017-04-12 19:26
@

**Comment by saneshark** [comment] 2017-04-12 19:31
@saintsoup52 thanks for adding that additional context. After some further thought on this and discussing internally, I think a good compromise would be to "warn" rather than "bail with errors" on inconsistent headers being provided.

Warnings are meant to address potential data discrepancy from an expected norm and to bring some transparency to how the data is used. Furthermore, by warning, we are effectively communicating that in the future we may deprecate certain capability as well. I would like for data uploads to become more normalized in the future. I know it's a tall order, but it's a necessary step in data integrity.

Would you be satisfied with it being a warning vs an error?

**Comment by saintsoup52** [comment] 2017-04-12 19:35
A warning is definitely in order... thank you BTW. Also as if on cue ED just completely redesigned their accreditation file.

I will send that over when I find it.

**Closed as completed** 2017-04-14 23:16 UTC
Labels: kudos, gibct

**Comment by patrickvinograd** [comment] 2017-04-15 00:59
I validated this in dev with the complaint and p911_tf files from current prod that had altered headers. Confirmed that they now upload correctly but generate warnings.

**Comment by saintsoup52** [comment] 2017-04-18 09:13
Thanks again for doing this... just to be sure... if the file is missing one of the critical columns (e.g., facility code in the WEAMS file) then the data service will not allow that csv to upload, correct?

**Comment by saneshark** [comment] 2017-04-20 20:14
@saintsoup52 yes, if a critical column is missing then the we will return an error, all other "non-critical" columns will result in "warning / notice."
